defmodule ExOura.TypeDecoder do
  @moduledoc """
  Decodes HTTP response bodies based on operation type specifications.

  This module handles the conversion of raw JSON responses from the Oura API into properly
  typed Elixir data structures. It supports various type conversions including dates,
  timestamps, unions, and complex nested structures generated by the OpenAPI code generator.

  ## Key Features

  - **Date/DateTime Parsing**: Automatically converts ISO8601 date and datetime strings
  - **Struct Creation**: Builds proper structs from generated OpenAPI client modules
  - **Union Type Handling**: Resolves union types based on actual data
  - **Nested Object Support**: Recursively processes nested objects and lists
  - **Null Safety**: Handles optional/nullable fields gracefully

  ## Type Conversion Rules

  - String dates (YYYY-MM-DD) → `Date` structs
  - ISO8601 timestamps → `DateTime` structs
  - Nested objects → Module structs (when available)
  - Lists → Recursively processed lists
  - Union types → Resolved based on data type

  ## Usage

  This module is used internally by the ExOura client and typically doesn't need to be
  called directly. The Client module automatically uses this to decode API responses.

  ## Examples

      # Internal usage by Client
      operation = %{response: %{200 => {MyModule, :t}}}
      {:ok, decoded} = TypeDecoder.decode_response(200, json_body, operation)
  """

  @doc """
  Decodes an HTTP response body based on the operation's type specifications.

  Takes the HTTP status code, response body, and operation metadata to determine
  the appropriate type conversion and decode the response into proper Elixir data structures.

  ## Parameters

  - `status` - HTTP status code from the response
  - `body` - Raw response body (typically parsed JSON)
  - `operation` - Operation metadata containing response type specifications

  ## Returns

  - `{:ok, decoded_data}` - Successfully decoded response
  - `{:error, :unable_to_decode}` - When type information is missing or invalid

  ## Type Resolution

  The function looks up the expected response type based on:
  1. The HTTP status code
  2. The operation's response type mapping
  3. Applies appropriate type conversions

  ## Examples

      # Decode a successful response
      operation = %{response: %{200 => {MyModule, :t}}}
      {:ok, result} = decode_response(200, %{field: "value"}, operation)

      # Handle unknown response types
      {:error, :unable_to_decode} = decode_response(200, body, %{})

  """
  @spec decode_response(status :: pos_integer(), body :: term(), operation :: map()) ::
          {:ok, term()} | {:error, :unable_to_decode}
  def decode_response(200 = _status, [], _operation), do: {:ok, []}

  def decode_response(status, body, operation) do
    case get_type(operation, status) do
      {:ok, response_type} ->
        {:ok, decode(body, maybe_prefer_dict_union(response_type, operation))}

      {:error, :unable_to_decode} = error ->
        error
    end
  end

  # Private functions for type resolution and decoding

  defp get_type(%{response: response} = _operation, status) do
    case response |> Map.new() |> Map.get(status, nil) do
      [type] ->
        {:ok, [type]}

      type when not is_nil(type) ->
        {:ok, type}

      _unexpected ->
        {:error, :unable_to_decode}
    end
  end

  defp maybe_prefer_dict_union({:union, types}, %{query: query}) when is_list(query) do
    if fields_requested?(query) do
      Enum.find(types, &dict_union_type?/1) || {:union, types}
    else
      {:union, types}
    end
  end

  defp maybe_prefer_dict_union(response_type, _operation), do: response_type

  # Core decoding functions

  defp decode(nil, _response_type), do: nil
  defp decode(value, {:string, :date}), do: Date.from_iso8601!(value)
  defp decode(value, {:string, "date"}), do: Date.from_iso8601!(value)
  defp decode(value, {:string, :"date-time"}), do: parse_datetime!(value)
  defp decode(value, {:string, "date-time"}), do: parse_datetime!(value)
  defp decode(value, {:union, types}), do: decode(value, union(value, types))
  defp decode(value, :string) when is_binary(value), do: value

  defp decode(value, [type]), do: Enum.map(value, &decode(&1, type))

  defp decode(%{} = value, {module, type}) do
    base = prepare_base(module)
    fields = module.__fields__(type)

    for {field_name, field_type} <- fields, reduce: base do
      decoded_value ->
        case Map.get(value, field_name) do
          nil ->
            decoded_value

          field_value ->
            decoded_field_value =
              field_value
              |> decode(field_type)
              |> maybe_parse_temporal_field(field_name)

            Map.put(decoded_value, field_name, decoded_field_value)
        end
    end
  end

  # Timestamp handling for modules ending with "Timestamp"
  defp decode(value, {type, :t}) do
    with true <- type |> to_string() |> String.ends_with?("Timestamp"),
         {:ok, dt, _} <- DateTime.from_iso8601(value) do
      dt
    else
      _error ->
        value
    end
  end

  # Generic string handling with smart date/datetime parsing
  defp decode(value, {:string, :generic}) when is_binary(value) do
    value
  end

  defp decode(value, _type), do: value

  # Helper to prepare base struct or map
  defp prepare_base(module) do
    Code.ensure_loaded(module)

    if function_exported?(module, :__struct__, 0) do
      struct(module)
    else
      %{}
    end
  end

  # Union type resolution logic
  defp union(nil, types) do
    if Enum.member?(types, :null), do: :null, else: hd(types)
  end

  defp union(value, types) do
    types
    |> Enum.reject(&(&1 == :null))
    |> Enum.sort_by(&union_priority/1)
    |> Enum.find(&union_type_match?(value, &1))
    |> case do
      nil -> raise "TypedDecoder: Unable to decode union type #{inspect(types)}"
      type -> type
    end
  end

  defp maybe_parse_temporal_field(value, field_name) when is_binary(value) do
    field_name
    |> to_string()
    |> temporal_field_parser()
    |> case do
      :date -> maybe_parse_date(value)
      :datetime -> maybe_parse_datetime(value)
      :none -> value
    end
  end

  defp maybe_parse_temporal_field(value, _field_name), do: value

  defp temporal_field_parser(field_name) do
    cond do
      field_name in ["day", "start_day", "end_day"] -> :date
      field_name == "timestamp" -> :datetime
      String.ends_with?(field_name, "_timestamp") -> :datetime
      String.ends_with?(field_name, "_datetime") -> :datetime
      String.ends_with?(field_name, "_time") -> :datetime
      String.ends_with?(field_name, "_at") -> :datetime
      field_name in ["bedtime_start", "bedtime_end"] -> :datetime
      true -> :none
    end
  end

  defp maybe_parse_date(value) do
    case Date.from_iso8601(value) do
      {:ok, date} -> date
      _error -> value
    end
  end

  defp maybe_parse_datetime(value) do
    case DateTime.from_iso8601(value) do
      {:ok, dt, _offset} -> dt
      _error -> value
    end
  end

  defp parse_datetime!(value) do
    case DateTime.from_iso8601(value) do
      {:ok, dt, _offset} -> dt
      {:error, reason} -> raise ArgumentError, "invalid ISO8601 datetime #{inspect(value)}: #{inspect(reason)}"
    end
  end

  defp union_priority({module, :t}) do
    if module |> Module.split() |> List.last() |> String.ends_with?("Dict"), do: 2, else: 0
  end

  defp union_priority(:map), do: 3
  defp union_priority(_type), do: 1

  defp union_type_match?(nil, :null), do: true
  defp union_type_match?(value, {:union, types}), do: Enum.any?(types, &union_type_match?(value, &1))
  defp union_type_match?(value, {_, :t}), do: is_map(value)
  defp union_type_match?(value, {:enum, _values}), do: is_binary(value)
  defp union_type_match?(value, {:string, _format}), do: is_binary(value)
  defp union_type_match?(value, :string), do: is_binary(value)
  defp union_type_match?(value, :integer), do: is_integer(value)
  defp union_type_match?(value, :number), do: is_number(value)
  defp union_type_match?(value, :boolean), do: is_boolean(value)
  defp union_type_match?(value, :map), do: is_map(value)
  defp union_type_match?(value, [type]), do: is_list(value) and Enum.all?(value, &union_type_match?(&1, type))
  defp union_type_match?(_value, _type), do: false

  defp fields_requested?(query), do: query |> Keyword.get(:fields) |> present_value?()

  defp present_value?(value) when value in [nil, ""], do: false
  defp present_value?(_value), do: true

  defp dict_union_type?({module, :t}) do
    module |> Module.split() |> List.last() |> String.ends_with?("Dict")
  end

  defp dict_union_type?(_type), do: false
end
